
package com.manh.jaxws.client.geenrated;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloSessionService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/HelloSessionService/HelloSession?WSDL")
public class HelloSessionService
    extends Service
{

    private final static URL HELLOSESSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSESSIONSERVICE_EXCEPTION;
    private final static QName HELLOSESSIONSERVICE_QNAME = new QName("http://server/", "HelloSessionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/HelloSessionService/HelloSession?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSESSIONSERVICE_WSDL_LOCATION = url;
        HELLOSESSIONSERVICE_EXCEPTION = e;
    }

    public HelloSessionService() {
        super(__getWsdlLocation(), HELLOSESSIONSERVICE_QNAME);
    }

    public HelloSessionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSESSIONSERVICE_QNAME, features);
    }

    public HelloSessionService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSESSIONSERVICE_QNAME);
    }

    public HelloSessionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSESSIONSERVICE_QNAME, features);
    }

    public HelloSessionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloSessionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloSession
     */
    @WebEndpoint(name = "HelloSessionPort")
    public HelloSession getHelloSessionPort() {
        return super.getPort(new QName("http://server/", "HelloSessionPort"), HelloSession.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloSession
     */
    @WebEndpoint(name = "HelloSessionPort")
    public HelloSession getHelloSessionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "HelloSessionPort"), HelloSession.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSESSIONSERVICE_EXCEPTION!= null) {
            throw HELLOSESSIONSERVICE_EXCEPTION;
        }
        return HELLOSESSIONSERVICE_WSDL_LOCATION;
    }

}
